-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Load raw data incrementally using cloud files
-- MAGIC 
-- MAGIC <img src='https://raw.githubusercontent.com/rportilla-databricks/dbt-asset-mgmt/main/images/BRONZE_loan_perf.png'>

-- COMMAND ----------

CREATE OR REFRESH STREAMING LIVE TABLE bronze_origination (
CONSTRAINT drop_MSA_rows_null EXPECT (METROPOLITAN_STATISTICAL_AREA IS NOT NULL) ON VIOLATION DROP ROW)
COMMENT "Ingestion of the sample orig data"
TBLPROPERTIES ("quality" = "bronze")
AS 
SELECT x.*, 'u' op FROM cloud_files(
"/loan_data_sergio/sample_orig_*.txt", "csv",
map("delimiter", "|", "schema",
  "CREDIT_SCORE STRING, FIRST_PAYMENT_DATE STRING, FIRST_TIME_HOMEBUYER_FLAG STRING, MATURITY_DATE STRING, METROPOLITAN_STATISTICAL_AREA STRING, MORTGAGE_INSURANCE_PERCENTAGE STRING, NUMBER_OF_UNITS STRING, OCCUPANCY_STATUS STRING, ORIGINAL_COMBINED_LOAN_TO_VALUE STRING, ORIGINAL_DEBT_TO_INCOME_RATIO STRING, ORIGINAL_UPB STRING, ORIGINAL_LOAN_TO_VALUE STRING, ORIGINAL_INTEREST_RATE STRING, CHANNEL STRING, PREPAYMENT_PENALTY_MORTGAGE_FLAG STRING, AMORTIZATION_TYPE STRING, PROPERTY_STATE STRING, PROPERTY_TYPE STRING, POSTAL_CODE STRING, LOAN_SEQUENCE_NUMBER STRING, LOAN_PURPOSE STRING, ORIGINAL_LOAN_TERM STRING, NUMBER_OF_BORROWERS STRING, SELLER_NAME STRING, SERVICER_NAME STRING, SUPER_CONFORMING_FLAG STRING, PRE_RELIEF_REFINANCE_LOAN_SEQUENCE_NUMBER STRING, PROGRAM_INDICATOR STRING, RELIEF_REFINANCE_INDICATOR STRING, PROPERTY_VALUATION_METHOD STRING, INTEREST_ONLY_INDICATOR STRING"
  )
) x

-- COMMAND ----------

CREATE OR REFRESH STREAMING LIVE TABLE bronze_svcg
COMMENT "Ingestion of the sample svcg data"
TBLPROPERTIES ("quality" = "bronze")
PARTITIONED BY (MONTHLY_REPORTING_PERIOD)
AS 
SELECT x.*, 'u' op  FROM cloud_files(
"/loan_data_sergio/sample_svcg_*.txt", "csv",
map("delimiter", "|", "schema",
  "LOAN_SEQUENCE_NUMBER STRING, MONTHLY_REPORTING_PERIOD STRING, CURRENT_ACTUAL_UPB STRING, CURRENT_LOAN_DELINQUENCY_STATUS STRING, LOAN_AGE STRING, REMAINING_MONTHS_TO_LEGAL_MATURITY STRING, DEFECT_SETTLEMENT_DATE STRING, MODIFICATION_FLAG STRING, ZERO_BALANCE_CODE STRING, ZERO_BALANCE_EFFECTIVE_DATE STRING, CURRENT_INTEREST_RATE STRING, CURRENT_DEFERRED_UPB STRING, DUE_DATE_OF_LAST_PAID_INSTALLMENT STRING, MI_RECOVERIES STRING, NET_SALE_PROCEEDS STRING, NON_MI_RECOVERIES STRING, EXPENSES STRING, LEGAL_COSTS STRING, MAINTENANCE_AND_PRESERVATION_COSTS STRING, TAXES_AND_INSURANCE STRING, MISCELLANEOUS_EXPENSES STRING, ACTUAL_LOSS_CALCULATION STRING, MODIFICATION_COST STRING, STEP_MODIFICATION_FLAG STRING, DEFERRED_PAYMENT_PLAN STRING, ESTIMATED_LOAN_TO_VALUE STRING, ZERO_BALANCE_REMOVAL_UPB STRING, DELINQUENT_ACCRUED_INTEREST STRING, DELINQUENCY_DUE_TO_DISASTER STRING, BORROWER_ASSISTANCE_STATUS_CODE STRING, CURRENT_MONTH_MODIFICATION_COST STRING, INTEREST_BEARING_UPB STRING"
  )
) x

-- COMMAND ----------


