-- Databricks notebook source
-- MAGIC %md-sandbox
-- MAGIC 
-- MAGIC # Your Lakehouse is the best Warehouse
-- MAGIC 
-- MAGIC 기존 데이터 웨어하우스는 다양한 데이터 및 사용 사례를 따라갈 수 없습니다. 비즈니스 민첩성을 위해서는 ML 모델의 통찰력을 갖춘 신뢰할 수 있는 실시간 데이터가 필요합니다.
-- MAGIC 
-- MAGIC 레이크하우스와 함께 작업하면 기존 BI 분석의 잠금을 해제할 수 있을 뿐만 아니라 완전한 보안을 유지하면서 전체 데이터에 직접 연결하는 실시간 애플리케이션도 사용할 수 있습니다.
-- MAGIC 
-- MAGIC <br>
-- MAGIC 
-- MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/raw/main/images/dbsql.png" width="700px" style="float: left" />
-- MAGIC 
-- MAGIC <div style="float: left; margin-top: 240px; font-size: 23px">
-- MAGIC   즉각적이고 유연한 컴퓨트 자원<br>
-- MAGIC   서버리스로 TCO 절감<br>
-- MAGIC   운영 관리 최소화<br><br>
-- MAGIC 
-- MAGIC   거버넌스 레이어 - row level<br><br>
-- MAGIC 
-- MAGIC   데이터 및 스키마 (star, data vault…)
-- MAGIC </div>

-- COMMAND ----------

-- MAGIC %md-sandbox
-- MAGIC # BI & Datawarehousing with Databricks SQL
-- MAGIC 
-- MAGIC <img style="float: right; margin-top: 10px" width="500px" src="https://github.com/databricks-demos/dbdemos-resources/raw/main/images/retail/lakehouse-churn/lakehouse-retail-c360-churn-3.png" />
-- MAGIC 
-- MAGIC 우리의 데이터 세트는 이제 고품질로 적절하게 수집되고 보호되며 조직 내에서 쉽게 검색할 수 있습니다.
-- MAGIC 
-- MAGIC Databricks SQL이 대화형 BI로 데이터 분석가 팀을 어떻게 지원하고 고객 이탈 분석을 시작하는지 살펴보겠습니다.
-- MAGIC 
-- MAGIC Databricks SQL을 시작하려면 왼쪽 상단 메뉴에서 SQL 보기를 엽니다.
-- MAGIC 
-- MAGIC 다음을 수행할 수 있습니다.
-- MAGIC 
-- MAGIC - 쿼리를 실행할 SQL Warehouse 생성
-- MAGIC - DBSQL을 사용하여 나만의 대시보드 구축
-- MAGIC - 모든 BI 도구(Tableau/PowerBI/..)를 연결하여 분석 실행

-- COMMAND ----------

-- MAGIC %md-sandbox
-- MAGIC ## Databricks SQL Warehouses: best-in-class BI engine
-- MAGIC 
-- MAGIC <img style="float: right; margin-left: 10px" width="600px" src="https://www.databricks.com/wp-content/uploads/2022/06/how-does-it-work-image-5.svg" />
-- MAGIC 
-- MAGIC Databricks SQL is a warehouse engine packed with thousands of optimizations to provide you with the best performance for all your tools, query types and real-world applications. <a href='https://www.databricks.com/blog/2021/11/02/databricks-sets-official-data-warehousing-performance-record.html'>It won the Data Warehousing Performance Record.</a>
-- MAGIC 
-- MAGIC This includes the next-generation vectorized query engine Photon, which together with SQL warehouses, provides up to 12x better price/performance than other cloud data warehouses.
-- MAGIC 
-- MAGIC **Serverless warehouse** provide instant, elastic SQL compute — decoupled from storage — and will automatically scale to provide unlimited concurrency without disruption, for high concurrency use cases.
-- MAGIC 
-- MAGIC Make no compromise. Your best Datawarehouse is a Lakehouse.
-- MAGIC 
-- MAGIC ### Creating a SQL Warehouse
-- MAGIC 
-- MAGIC SQL Wharehouse are managed by databricks. [Creating a warehouse](/sql/warehouses) is a 1-click step: 

-- COMMAND ----------

-- MAGIC %md-sandbox
-- MAGIC 
-- MAGIC ## Creating your first Query
-- MAGIC 
-- MAGIC <img style="float: right; margin-left: 10px" width="600px" src="https://raw.githubusercontent.com/QuentinAmbard/databricks-demo/main/retail/resources/images/lakehouse-retail/lakehouse-retail-dbsql-query.png" />
-- MAGIC 
-- MAGIC Our users can now start running SQL queries using the SQL editor and add new visualizations.
-- MAGIC 
-- MAGIC By leveraging auto-completion and the schema browser, we can start running adhoc queries on top of our data.
-- MAGIC 
-- MAGIC While this is ideal for Data Analyst to start analysing our customer Churn, other personas can also leverage DBSQL to track our data ingestion pipeline, the data quality, model behavior etc.
-- MAGIC 
-- MAGIC Open the [Queries menu](/sql/queries) to start writting your first analysis.

-- COMMAND ----------

-- MAGIC %md-sandbox
-- MAGIC 
-- MAGIC ## Creating our Churn Dashboard
-- MAGIC 
-- MAGIC <img style="float: right; margin-left: 10px" width="600px" src="https://raw.githubusercontent.com/QuentinAmbard/databricks-demo/main/retail/resources/images/lakehouse-retail/lakehouse-retail-churn-dbsql-dashboard.png" />
-- MAGIC 
-- MAGIC The next step is now to assemble our queries and their visualization in a comprehensive SQL dashboard that our business will be able to track.
-- MAGIC 
-- MAGIC The Dashboard has been loaded for you. Open the [DBSQL Churn Dashboard](/sql/dashboards/19394330-2274-4b4b-90ce-d415a7ff2130) to start reviewing our Churn stats.

-- COMMAND ----------

-- MAGIC %md-sandbox
-- MAGIC 
-- MAGIC ## Using Third party BI tools
-- MAGIC 
-- MAGIC <iframe style="float: right" width="560" height="315" src="https://www.youtube.com/embed/EcKqQV0rCnQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
-- MAGIC 
-- MAGIC SQL warehouse can also be used with an external BI tool such as Tableau or PowerBI.
-- MAGIC 
-- MAGIC This will allow you to run direct queries on top of your table, with a unified security model and Unity Catalog (ex: through SSO). Now analysts can use their favorite tools to discover new business insights on the most complete and freshest data.
-- MAGIC 
-- MAGIC To start using your Warehouse with third party BI tool, click on "Partner Connect" on the bottom left and chose your provider.

-- COMMAND ----------

-- MAGIC %md-sandbox
-- MAGIC ## Going further with DBSQL & Databricks Warehouse
-- MAGIC 
-- MAGIC Databricks SQL offers much more and provides a full warehouse capabilities
-- MAGIC 
-- MAGIC <img style="float: right" width="400px" src="https://raw.githubusercontent.com/QuentinAmbard/databricks-demo/main/retail/resources/images/lakehouse-retail/lakehouse-retail-dbsql-pk-fk.png" />
-- MAGIC 
-- MAGIC ### Data modeling
-- MAGIC 
-- MAGIC Comprehensive data modeling. Save your data based on your requirements: Data vault, Star schema, Inmon...
-- MAGIC 
-- MAGIC Databricks let you create your PK/FK, identity columns (auto-increment): `dbdemos.install('identity-pk-fk')`
-- MAGIC 
-- MAGIC ### Data ingestion made easy with DBSQL & DBT
-- MAGIC 
-- MAGIC Turnkey capabilities allow analysts and analytic engineers to easily ingest data from anything like cloud storage to enterprise applications such as Salesforce, Google Analytics, or Marketo using Fivetran. It’s just one click away. 
-- MAGIC 
-- MAGIC Then, simply manage dependencies and transform data in-place with built-in ETL capabilities on the Lakehouse (Delta Live Table), or using your favorite tools like dbt on Databricks SQL for best-in-class performance.
-- MAGIC 
-- MAGIC ### Query federation
-- MAGIC 
-- MAGIC Need to access cross-system data? Databricks SQL query federation let you define datasources outside of databricks (ex: PostgreSQL)
-- MAGIC 
-- MAGIC ### Materialized view
-- MAGIC 
-- MAGIC Avoid expensive queries and materialize your tables. The engine will recompute only what's required when your data get updated. 

-- COMMAND ----------

-- MAGIC %md
-- MAGIC 
-- MAGIC # Taking our analysis one step further: Predicting Churn
-- MAGIC 
-- MAGIC Being able to run analysis on our past data already gives us a lot of insight. We can better understand which customers are churning evaluate the churn impact.
-- MAGIC 
-- MAGIC However, knowing that we have churn isn't enough. We now need to take it to the next level and build a predictive model to determine our customers at risk of churn to be able to increase our revenue.
-- MAGIC 
-- MAGIC Let's see how this can be done with [Databricks Machine Learning notebook]($../04-Data-Science-ML/04.1-automl-churn-prediction) | go [Go back to the introduction]($../00-churn-introduction-lakehouse)
